### ISSUE TITLE
November Manual Scheduling

### ISSUE THREAD

**Issue by Robinmcgvr** [Robinmcgvr/Manual-Scheduling#1]
Hi Jonathan and Lynne,

I have set up a new repository for logging the progress of Manual Scheduling and any other comments or actions required.

Please accept the invitation to join this and we can get it going.

Many thanks

Robin

**Comment by Robinmcgvr** [comment]
Complete as of 02/01/2021
Taiwan
Belgium
Switzerland
Ukraine

**Comment by Robinmcgvr** [comment]
To do
Russia 5-TV (Petersburg 5) to be prepped, analysed and relevant titles entered - by Robin

**Comment by Lynne12** [comment]
@Robinmcgvr Brazil and Mexico need to be prepped.

**Comment by Lynne12** [comment]
Ukraine was completed on 3rd December.

**Comment by Robinmcgvr** [comment]
@Lynne12 
I should get to the Latam  November prepping either end of this week or beginning of next.
Finishing off the Europe October Paramount reports this week.

**Comment by Robinmcgvr** [comment]
@Lynne12 
Brazil Discovery Kids, Prepped and entered - this can be marked off as done!

**Comment by Robinmcgvr** [comment]
@Lynne12 
Mexico Disc Kids & Nick , prepped and entered - these can be marked off as done!

**Comment by Robinmcgvr** [comment]
@Lynne12 
TAIWAN FOX MOVIES Prepped and ready - I imagine that no-one is currently available to work on this - but have emailed it to you anyway.
N.B. No titles to enter for Star Chines Movies or Fox HD

**Comment by Robinmcgvr** [comment]
@Lynne12 
Russia - Petersburg 5 , prepped and checked, no titles found to enter.
This can now be marked off as done

**Comment by Lynne12** [comment]
Japan scheduled up to and including 27th November, for all channels.  We are waiting on the final November magazine from Taka, the Japanese translator.

**Comment by Lynne12** [comment]
**Countries complete:-**

- [x] UKRAINE
- [x] JAPAN
- [x] BELGIUM
- [x] RUSSIA
- [x] TAIWAN
- [x] BRAZIL
- [x] MEXICO
- [x] SWITZERLAND

**Comment by Lynne12** [comment]
@Robinmcgvr November manual scheduling is complete.
