### ISSUE TITLE
PARAMOUNT ONLY CHANNELS MANUAL SCHEDULING - AUG 2021

### ISSUE THREAD

**Issue by Robinmcgvr** [Robinmcgvr/Manual-Scheduling#11]
MIDDLE EAST
MBC ACTION - 17/08/2021 (INC)
MBC2 - 17/08/2021(INC)
MBC4 - 17/08/2021 (INC)
MBC - 17/08/2021 (INC)
MBC3 - 17/08/2021 (INC)

**Comment by Robinmcgvr** [comment]
TURKEY
ALL CHANNELS TO 18/08/2021 (INC)

**Comment by Robinmcgvr** [comment]
PHILIPPINES
TV5 - 18/08/2021 (INC)

**Comment by Robinmcgvr** [comment]
SPAIN
TVG - 17/08/2021 (INC)
TELEMADRID - 17/08/2021 (INC)
TV3 - 17/08/2021 (INC)

**Comment by Lynne12** [comment]
@Robinmcgvr I have assigned Jackie too, so that she can log the updates when I am away.

**Comment by Robinmcgvr** [comment]
MIDDLE EAST 
MBC ACTION - 26/08/2021 (INC)
MBC4 - 26/08/2021 (INC)
MBC2 - 24/08/2021 PROBLEMS WITH DATA AGAIN - NO INFO FOR 23/08/2021 OR 25/08/2021 ( will revisit next week)
MBC - 26/08/2021 (INC)
MBC3 - 23/08/2021

**Comment by Robinmcgvr** [comment]
TURKEY 
ALL CHANNELS - 21/08/2021

**Comment by Robinmcgvr** [comment]
SPAIN
TVG - 20/08/201 (INC)
TV3 - 20/08/2021 (INC)
TELMADRID - 20/08/2021 (INC)

**Comment by Lynne12** [comment]
> MIDDLE EAST
> MBC ACTION - 26/08/2021 (INC)
> MBC4 - 26/08/2021 (INC)
> MBC2 - PROBLEMS WITH DATA AGAIN - NO INFO FOR 23/08/2021 OR 25/08/2021 ( will revisit next week)
> MBC - 26/08/2021 (INC)
> MBC3 - 23/08/2021

@Robinmcgvr are the other dates done to 26th, for MBC2?

**Comment by Lynne12** [comment]
@Robinmcgvr Dawn is working one day today.  She has started Paramount from your latest updates and I will update here later.

**Comment by Robinmcgvr** [comment]
@Lynne12 
MBC2 only done to 24th , there was not other data available on friday
Hopefully the site will be behaving again today

**Comment by Robinmcgvr** [comment]
@Lynne12 
data for the 23rd & 25th is there now on the sites now, could you let Dawn know?

**Comment by Lynne12** [comment]
TURKEY - all channels 23/8/2021 (Inc)

MIDDLE EAST - no further updates

PHILIPPINES - 23-29/8/2021 (Inc) Dawn normally does a week of this on a Monday.  Last week you only did 3 days to 18th, so 19th-22nd is no longer available on the website.  Could you fill in the gaps if you have another source, please Robin.

SPAIN
TVG - 25/8/2021 (Inc)
TLMA - 24/8/2021 (Inc)
TV3 - 23/8/2021 (Inc)

**Comment by Lynne12** [comment]
> @Lynne12
> data for the 23rd & 25th is there now on the sites now, could you let Dawn know?

She has finished Paramount for today and is now verifying, so you may want to make a note for when you take over again to add those in.

**Comment by Robinmcgvr** [comment]
There is kablam data for philippines to the 21st, I didn't realise she was only doing a quick version on the paramount

**Comment by Robinmcgvr** [comment]
Anyway never mind - I'll sort it out

**Comment by Robinmcgvr** [comment]
MIDDLE EAST
MBC ACTION - 29/08/2021 (INC)
MBC2 - 23 & 25/08 NOW DONE - NO DATA BEYOND 25TH - hopefully downloads will capture this if it returns 
MBC - 29/08/2021 (INC)
MBC3 - 25/08/2021 (INC) - NO DATA BEYOND THIS DATE CURRENTLY

**Comment by Robinmcgvr** [comment]
PHILIPPINES - 29/08/2021 -PARTIAL ON THIS DATE - ONE UNIDENTIFIED TITLE HOPE TO GET MORE INFO ON THIS LATER

**Comment by Robinmcgvr** [comment]
MIDDLE EAST ALL CHANNELS TO 30/08/2021 (INC)

**Comment by Robinmcgvr** [comment]
SPAIN ALL CHANNELS TO EARLY HOURS 28/08/2021

**Comment by Robinmcgvr** [comment]
TURKEY ALL CHANNELS TO 29/08/2021 (INC)
