### ISSUE TITLE
September 2021 Manual Scheduling

### ISSUE THREAD

**Issue by Robinmcgvr** [Robinmcgvr/Manual-Scheduling#14]
Countries complete:-

- [x] UKRAINE
- [x] JAPAN
- [x] BELGIUM - PREPPED AND EMAILED
- [x] RUSSIA
- [x] TAIWAN
- [x] BRAZIL - PREPPED AND EMAILED
- [x] MEXICO - PREPPED AND EMAILED
- [x] SWITZERLAND
- [x] TURKEY
- [x] MIDDLE EAST 
- [x] PHILIPPINES
- [x] SPAIN

**Comment by Robinmcgvr** [comment]
@Lynne12 
Ukraine all channels done up to 12/09/2021 (inc) plus early hours of 13th for some

**Comment by Robinmcgvr** [comment]
Paramount manual scheduling -
TURKEY 
ATV - 12/09/2021 (INC EARLY HOURS OF 13TH)
TV8 -12/09/2021
SHOW TV - 12/09/2021 (INC EARLY HOURS OF 13TH)
KANAL D - 12/09/2021 (INC EARLY HOURS OF 13TH)
STAR TV - 11/09/2021
KANAL 7 - 15/09/2021
TRT1 - 15/09/2021

MIDDLE EAST
MBC2 - 11/09/2021 (HALF WAY)
MBC ACTION

**Comment by Lynne12** [comment]
@Robinmcgvr data prep is required for Belgium, Brazil, Mexico, Switzerland, please.  Taiwan too, if anything on the channels FOX and STAR Chinese Movies.

**Comment by Lynne12** [comment]
@Robinmcgvr any news on the above, please?

**Comment by Robinmcgvr** [comment]
@Lynne12 
Sorry still busy with reports at the moment, will be able to do some tomorrow or monday

**Comment by Robinmcgvr** [comment]
Re Taiwan , nothing further only Fox Movies had data

**Comment by Robinmcgvr** [comment]
Actually you can have Brazil now I did this last week but was waiting til had time to translate the titles and do the Mexico

**Comment by Robinmcgvr** [comment]
Mexico prepped and emailed - NO TITLES TO ENTER FOR NICK THIS MONTH
Belgium prepped and emailed - NO TITLES TO ENTER FOR VTM KIDS THIS MONTH

**Comment by Robinmcgvr** [comment]
@Lynne12 
Swiss man sched done - nothing to enter for 5+ or TV25

**Comment by Robinmcgvr** [comment]
Russia done - no titles to enter

**Comment by Lynne12** [comment]
@Robinmcgvr @JackieColes September manual scheduling is complete.
