### ISSUE TITLE
Training schedulers to Manually input

### ISSUE THREAD

**Issue by Robinmcgvr** [Robinmcgvr/Manual-Scheduling#19]
@Lynne12 
Are you going to go ahead with the plan to train the scheduled data inputters to manually schedule this year?
This was something we discussed previously.
There are instructions I drafted before which could be used to speed up the training process. It is something that should be pretty simple to transfer skills to.

**Comment by Lynne12** [comment]
Yes, that's the plan.  Let me know when the December data is prepped.

**Comment by Lynne12** [comment]
@Robinmcgvr any update on the December data, please, with a rough idea when I can expect it?

**Comment by Robinmcgvr** [comment]
@Lynne12 
brazil and Mexico is ready for you, I am working on big BMI check but will try and get belgium prepped today

**Comment by Lynne12** [comment]
Thanks Robin!

**Comment by Lynne12** [comment]
@Robinmcgvr Jelena has been trained on Manual Scheduling.
