### ISSUE TITLE
December Manual Scheduling

### ISSUE THREAD

**Issue by Robinmcgvr** [Robinmcgvr/Manual-Scheduling#2]
December Manual Scheduling complete as of 02/01/2021 
See below

**Comment by Robinmcgvr** [comment]
As of 04/01/2021
TURKEY
MIDDLE EAST
PHILIPPINES
SPAIN

**Comment by Lynne12** [comment]
Prepping required for:-

BELGIUM - READY - SENT TO LYNNE - DONE
RUSSIA - DONE
TAIWAN - READY - SENT TO LYNNE - DONE
BRAZIL - READY - SENT TO LYNNE - DONE
MEXICO - READY - SENT TO LYNNE - DONE
SWITZERLAND - READY - SENT TO LYNNE - DONE

**Comment by Robinmcgvr** [comment]
@Lynne12 
HK STAR MOVIES HD Translations prepped and emailed to you

**Comment by Robinmcgvr** [comment]
Taiwan Fox Movies data file prepared

**Comment by Lynne12** [comment]
@Robinmcgvr you have sent me November Taiwan Fox Movies, which has already been input

**Comment by Lynne12** [comment]
@Robinmcgvr I am not sure why you have deleted my comment.  You haven't sent me a December Taiwan movies file?  You resent me November, which has already been processed.

**Comment by Lynne12** [comment]
> Taiwan Fox Movies data file prepared

Please email me the file.

**Comment by Robinmcgvr** [comment]
@Lynne12 
december taiwan file now sent

**Comment by Robinmcgvr** [comment]
SWITZERLAND & BELGIUM DATA PREPPED AND SENT TO LYNNE
N.B. Two titles included in the S1 data can be ignored, they slipped through the net - they are 'Facing/Pablo Escobar' & 'Facing/Saddam Hussein'. 22&23/12 2020 
Please delete those rows if you pass this on to anyone to work on.

**Comment by Lynne12** [comment]
**Countries complete:-**

- [x] UKRAINE
- [x] JAPAN
- [x] BELGIUM
- [x] RUSSIA
- [x] TAIWAN
- [x] BRAZIL
- [x] MEXICO
- [x] SWITZERLAND
- [x] TURKEY
- [x] MIDDLE EAST
- [x] PHILIPPINES
- [x] SPAIN

**Comment by Lynne12** [comment]
@Robinmcgvr data prep is required for Russia, please.

**Comment by Robinmcgvr** [comment]
I will do that  preparation and entering of the data, myself as is usual, when I get the time.
Right now I am rather busy with other stuff but as the work is for me anyway it can hang on.

**Comment by Robinmcgvr** [comment]
@Lynne12 
Russia done

**Comment by Robinmcgvr** [comment]
We are just waiting on the Japan data now

**Comment by Lynne12** [comment]
Manual scheduling, December 2020, complete. NKT1 Japan has not been entered for December, as per previous email discussions.
