### ISSUE TITLE
AUGUST SPAIN AND MIDDLE EAST MANUAL SCHEDULING

### ISSUE THREAD

**Issue by Robinmcgvr** [Robinmcgvr/Manual-Scheduling#26]
SPAIN - TLMA -> 23/08/2022
MIDDLE EAST :
MBC2 -> 24/08/2022 
MBC ACTION -> 23/08/2022
MBC1 -> 23/08/2022
MBC3 -> 23/08/2022
MBC4 -> 23/08/2022

**Comment by Lynne12** [comment]
> SPAIN - TLMA -> 23/08/2022 MIDDLE EAST : MBC2 -> 24/08/2022 MBC ACTION -> 23/08/2022 MBC1 -> 23/08/2022 MBC3 -> 23/08/2022 MBC4 -> 23/08/2022

Thanks Robin, duly logged!

**Comment by Lynne12** [comment]
@Robinmcgvr Dawn is back today and will be resuming the scheduling.  She did not receive an email from you, so we have only been able to provide the dates logged above.  Please let me know if these are still the current position.

**Comment by Lynne12** [comment]
@Robinmcgvr all channels now scheduled to the month end.
