### ISSUE TITLE
IRISH CHANNEL GAPS 

### ISSUE THREAD

**Issue by Robinmcgvr** [Robinmcgvr/Manual-Scheduling#35]
RTE2 - 19/01/2023, 02/02/2023, 28/02/2023 - loaded
RTE1 - 19/01/2023, 13/02/2023, 15/3/2023, 16/3/2023, 18/3/2023 - loaded
**TG4** - 28/01/2023, 08/02/2023, 13/02/2023, 15/02/2023
**TV3I** - 17/01/2023, 28/01/2023, 30/01/2023, 07/03/2023

**Comment by Lynne12** [comment]
@Robinmcgvr RTE2 is missing from 28th February up to the current date.  I have raised a separate issue on the Kapow repository.

**Comment by Lynne12** [comment]
@Robinmcgvr RTE1 & RTE 2 missing dates above loaded from rte.ie

**Comment by Robinmcgvr** [comment]
tv3i - jan, feb missing days now added

**Comment by Robinmcgvr** [comment]
tg4 missing days added
