### ISSUE TITLE
January 2021 Manual Scheduling

### ISSUE THREAD

**Issue by Lynne12** [Robinmcgvr/Manual-Scheduling#4]
**Countries complete:-**

- [x] UKRAINE
- [x] JAPAN (with the exception of NKT1)
- [x] BELGIUM
- [x] RUSSIA
- [x] TAIWAN
- [x] BRAZIL
- [x] MEXICO
- [x] SWITZERLAND
- [x] TURKEY Missing 23rd & 24th all channels
- [x] MIDDLE EAST
- [x] PHILIPPINES
- [x] SPAIN

**Comment by Lynne12** [comment]
@Robinmcgvr data prep is required for Belgium, Russia, Taiwan, Brazil, Mexico, Switzerland, please.

**Comment by Robinmcgvr** [comment]
I will get onto it when I am free, again I do most of the work myself for this ...

**Comment by Lynne12** [comment]
@Robinmcgvr you don't input most of these countries.  Belgium, Taiwan, Brazil, Mexico, Switzerland, December work has all been done by myself.  We don't want to get into a pattern where it becomes urgent, as has happened in the past and it is prepped when we are not in a good position to work on it.

**Comment by Robinmcgvr** [comment]
@Lynne12 
Sorry I just have too ,much on my plate to work on this in any way right now.
WGA overdue, had to lots of special work for Paramount , so it will just have to wait unless you want to pull and analyse the data?

**Comment by Lynne12** [comment]
> @Robinmcgvr data prep is required for Belgium, Russia, Taiwan, Brazil, Mexico, Switzerland, please.

This was a standard reminder.  You know when it is required, so will wait for you to prep it.  But should just be mindful that this gets worked in to priorities as and when we have scope, which I believe Jonathan explained to you before, so if it suddenly becomes urgent later down the line we may not be able to jump onto it immediately.  Many thanks.

**Comment by Robinmcgvr** [comment]
@Lynne12 
Yes I know but when other things have high priority other things have to get bumped down the list , it is is just the way it goes sometimes isn't it?
And as always if no-one available I will do the work as has been the case most of the time for years.

**Comment by Lynne12** [comment]
@Robinmcgvr I wasn't asking you to make it high priority.  It was a reminder to work in when you could, as I have always done.  Perhaps it would be better if you have your own reminder, going forwards.  This has been needlessly drawn out and as you say there is too much work for everybody to do to waste time like this.

**Comment by Robinmcgvr** [comment]
@Lynne12 
Taiwan Fox Movies (FKS Star Movies) file prepped and sent to you.
No titles to enter for Fox or Star Chinese Movies

**Comment by Robinmcgvr** [comment]
@Lynne12 
BRAZIL AND MEXICO DISC KIDS & NICK PREPPED
N.B. No Movies to enter for Mexico Nick
BRAZIL - Disc Kids entered (only 5 entries)
MEXICO - Disc Kids emailed

**Comment by Robinmcgvr** [comment]
@Lynne12 
BELGIUM MANUAL SCHED PREPPED AND READY

**Comment by Robinmcgvr** [comment]
Switzerland Manual sched prepped and emailed

**Comment by Robinmcgvr** [comment]
test

**Comment by Lynne12** [comment]
> Switzerland Manual sched prepped and emailed

Can you confirm the status of 5+, there is no data for this on the Excel file?

**Comment by Robinmcgvr** [comment]
There were no Movies to enter for channel 5+

**Comment by Robinmcgvr** [comment]
@Lynne12 
Russia Pet 5 scheduling complete

**Comment by Lynne12** [comment]
@Robinmcgvr @JackieColes January manual scheduling complete

**Comment by Robinmcgvr** [comment]
Can you let me know what the situation is with NKT1 now please?
ie has this been entered now?

**Comment by Lynne12** [comment]
We are only starting to enter from February 2021 (which Taka has translated, if there is anything on the channel).  Debbie hasn't started on this yet.  You will need to refer back to the earlier emails for details of what was said about the channel.

**Comment by Robinmcgvr** [comment]
Thanks that was the answer I needed 'We are only starting to enter from February 2021 '
