### ISSUE TITLE
Australian channel gaps

### ISSUE THREAD

**Issue by Lynne12** [Robinmcgvr/Manual-Scheduling#40]
GWNP
PR16
NBN3
WINT
QTVT
All missing 7th March 2023

**Comment by Robinmcgvr** [comment]
OK I think I've got these covered from ontvtonight.com.au data
[AUSTRALIA 07032023 GAP FILLING WORK.xlsx](https://github.com/Robinmcgvr/Manual-Scheduling/files/11168635/AUSTRALIA.07032023.GAP.FILLING.WORK.xlsx)
I WILL PROCESS THIS AT SOME POINT

**Comment by Robinmcgvr** [comment]
Oh dear, bad news on this, it is actually data for 08/03 that is missing, not loaded, and unfortunately I can't find alternative source data for that date.
So we are going to be stuck with the gap
