### ISSUE TITLE
February 2021 Manual Scheduling

### ISSUE THREAD

**Issue by Lynne12** [Robinmcgvr/Manual-Scheduling#5]
**Countries complete:-**

- [x] UKRAINE
- [x] JAPAN
- [x] BELGIUM
- [x] RUSSIA - no titles entered
- [x] TAIWAN
- [x] BRAZIL
- [x] MEXICO
- [x] SWITZERLAND
- [x] TURKEY
- [x] MIDDLE EAST
- [x] PHILIPPINES
- [x] SPAIN

**Comment by Robinmcgvr** [comment]
Greece - Filmg (Nova Cinema 1) may require manual scheduling for at least 18/02/2021 via Nova.gr
If there are more days that need it for Feb , I will add details here too.

**Comment by Robinmcgvr** [comment]
MANUAL SCHEDULING FILES PREPARATION
- [x] BELGIUM
- [X] BRAZIL
- [X] MEXICO
- [X] SWITZERLAND
- [X] RUSSIA
- [X] TAIWAN

**Comment by Lynne12** [comment]
@Robinmcgvr February manual scheduling is now complete.
