### ISSUE TITLE
SERBIA - PINK & PINK PREMIUM 27/28 SEPT 2023

### ISSUE THREAD

**Issue by Robinmcgvr** [Robinmcgvr/Manual-Scheduling#50]
These two channels will need manual scheduling, either from pdfs saved or via aladin or ,muj.tv taking into account time difference on former and being a day out on the latter

**Comment by Lynne12** [comment]
@Robinmcgvr just a reminder re the above two channels that need to be manually scheduling for these missing dates.

**Comment by Robinmcgvr** [comment]
Thanks for the reminder, I will tackle once I finish the Q2 stuff

**Comment by Robinmcgvr** [comment]
OK done - there was only one title to enter for Pink
