### ISSUE TITLE
Japan WowWow 

### ISSUE THREAD

**Issue by Robinmcgvr** [Robinmcgvr/Manual-Scheduling#53]
https://www.wowow.co.jp/english/pdf/pg2311.pdf
the above link takes you to the Wowwow monthly pdf , which can be helpful sometimes. The month can be changed by editing the url

**Comment by Lynne12** [comment]
@Robinmcgvr unfortunately this gives no more detail than Taka supplies, when he marks up the magazine, from an inputting point of view.

**Comment by Robinmcgvr** [comment]
yes but it is sometimes easier to see the times on this or when the mags go missing.
I refer to it quite a bit for checking, so just thought there might be times where you would find it helpful
