### ISSUE TITLE
March 2021 Manual Scheduling

### ISSUE THREAD

**Issue by Lynne12** [Robinmcgvr/Manual-Scheduling#6]
Countries complete:-

- [x]  UKRAINE
- [x]  JAPAN
- [x]  BELGIUM
- [x]  RUSSIA
- [x]  TAIWAN
- [x]  BRAZIL
- [x]  MEXICO
- [x]  SWITZERLAND
- [x]  TURKEY
- [x]  MIDDLE EAST
- [x]  PHILIPPINES
- [x]  SPAIN

**Comment by Lynne12** [comment]
MANUAL SCHEDULING FILES PREPARATION

 - [x] BELGIUM
- [x]  BRAZIL
- [x]  MEXICO
- [X]  SWITZERLAND
- [x] RUSSIA
- [x] TAIWAN

**Comment by Robinmcgvr** [comment]
MEXICO AND BRAZIL PREPPED & EMAILED - N.B. NO MOVIES FOUND ON NICK/MEXICO

**Comment by Robinmcgvr** [comment]
Belgium prepped and emailed - n.b. no movies found for VTM Kids

**Comment by Robinmcgvr** [comment]
Taiwan prepped and emailed

**Comment by Robinmcgvr** [comment]
I know that the Switzerland data is still outstanding - I will prep and enter this myself

**Comment by Lynne12** [comment]
@Robinmcgvr Russia too, when you are able.

**Comment by Robinmcgvr** [comment]
SWITZERLAND PREPPED

**Comment by Lynne12** [comment]
> I know that the Switzerland data is still outstanding - I will prep and enter this myself

@Robinmcgvr you said you would be entering this data yourself.  Please confirm that this is the case.

**Comment by Robinmcgvr** [comment]
Yep I am still entering , that was logged for my reference

**Comment by Robinmcgvr** [comment]
Russia and Switzerland done

**Comment by Lynne12** [comment]
@Robinmcgvr March manual scheduling complete.
