### ISSUE TITLE
Australia - Ourguide,com.au 05/02 data needs filling

### ISSUE THREAD

**Issue by Robinmcgvr** [Robinmcgvr/Manual-Scheduling#62]
We are missing all data for 05/02/2024 - this will not be recoverable

**Comment by Robinmcgvr** [comment]
same applies to yourtv.com.au unfortunately (same date 05/02)

**Comment by Lynne12** [comment]
@Robinmcgvr can this be closed now?

**Comment by Robinmcgvr** [comment]
No this data needs manually filling

**Comment by Robinmcgvr** [comment]
if this data can be filled then it should, if not note the gap

**Comment by Robinmcgvr** [comment]
Ok have manually scheduled these channels using ontvtonight.com.au
